In [54]:
import pymongo

client = pymongo.MongoClient("mongodb+srv://KPKAVIN:kasaan@cluster0.3bc5s5h.mongodb.net/?retryWrites=true&w=majority")
db = client.telephone_directory


a={"Name":'',"Phone number":'',"Address":{'Door_no':'','Street_name':'','Area':'','State':'','Pincode':''},}

n=input("Enter Name: " )
a["Name"]=n

d=input("Enter Door no.: ")
a["Address"]['Door_no']=d
s=input("Enter street name: ")
a["Address"]['Street_name']=s
c=input("Enter place name: ")
a["Address"]['Area']=c
st=input("Enter state name: ")
a["Address"]['State']=st

def pincode():
  p=input("Enter pincode: ")
  if len(p)==6 and p.isnumeric()==True:
    a["Address"]['Pincode']=p
  else:
    print("pincode must be in six digits")
    pincode()
pincode()


def phonenumber():
  try:
    Pho=input("Enter Ph.no: ")
    if len(Pho)==10 and Pho.isnumeric()==True:
      a["Phone number"]=Pho
    else:
      print('phonenumber must be 10 digits')
      phonenumber()
  except ValueError:
    print('Enter valid number not alphabets and special characters')
    phonenumber()
phonenumber()

m=[]
for t in a:
  m.append(a[t]) 
g=[]
for n in m:
  if n!='':
    g.append(n)
# print(len(g))

p=[]
for k in (a["Address"]):
  p.append(a["Address"][k])
l=[]
for y in p:
  if y!='':
    l.append(y)
# print(len(l))
if len(g)==3 and len(l)==5:
  db.phonebook.insert_one(a)
else:
  print(a)
  print('Enter values in the missing places')

Enter Name: Gerald
Enter Door no.: 86
Enter street name: M.A.koil street
Enter place name: butt road
Enter state name: Tamilnadu
Enter pincode: 123456
Enter Ph.no: 9638521476

In [55]:
#1.Make a query to find records you just created.
f=db.phonebook.find()
for i in f:
  print(i)
#Answer:
# {'_id': ObjectId('63a17edbcdbec8b76482581f'), 'Name': 'Xavier', 'Phone number': '1234567894', 'Address': {'Door_no': '4/70', 'Street_name': 'St.Antony street', 'Area': 'St.Thomas Mount', 'State': 'Tamil nadu', 'Pincode': '123456'}}
# {'_id': ObjectId('63a181afcdbec8b764825822'), 'Name': 'Monisha', 'Phone number': '4567891235', 'Address': {'Door_no': '12', 'Street_name': 'gold street', 'Area': 'bangalore', 'State': 'karnataka', 'Pincode': '235614'}}
# {'_id': ObjectId('63a181f1cdbec8b764825824'), 'Name': 'Tim', 'Phone number': '7895461235', 'Address': {'Door_no': '56', 'Street_name': 'park avenue', 'Area': 'chennai', 'State': 'Tamilnadu', 'Pincode': '123456'}}
# {'_id': ObjectId('63a18272cdbec8b764825826'), 'Name': 'Gerald', 'Phone number': '9638521476', 'Address': {'Door_no': '86', 'Street_name': 'M.A.koil street', 'Area': 'butt road', 'State': 'Tamilnadu', 'Pincode': '123456'}}

{'_id': ObjectId('63a17edbcdbec8b76482581f'), 'Name': 'Xavier', 'Phone number': '1234567894', 'Address': {'Door_no': '4/70', 'Street_name': 'St.Antony street', 'Area': 'St.Thomas Mount', 'State': 'Tamil nadu', 'Pincode': '123456'}}
{'_id': ObjectId('63a181afcdbec8b764825822'), 'Name': 'Monisha', 'Phone number': '4567891235', 'Address': {'Door_no': '12', 'Street_name': 'gold street', 'Area': 'bangalore', 'State': 'karnataka', 'Pincode': '235614'}}
{'_id': ObjectId('63a181f1cdbec8b764825824'), 'Name': 'Tim', 'Phone number': '7895461235', 'Address': {'Door_no': '56', 'Street_name': 'park avenue', 'Area': 'chennai', 'State': 'Tamilnadu', 'Pincode': '123456'}}
{'_id': ObjectId('63a18272cdbec8b764825826'), 'Name': 'Gerald', 'Phone number': '9638521476', 'Address': {'Door_no': '86', 'Street_name': 'M.A.koil street', 'Area': 'butt road', 'State': 'Tamilnadu', 'Pincode': '123456'}}

In [60]:
#2.Modify the records, use the update_one() method. The update_one() method requires two arguments, query and update.
g=db.phonebook.update_one({"Name":"Gerald"},{"$set":{"Address.Street_name":"Silver street"}})
n=db.phonebook.find({"Name":"Gerald"})
for i in n:
  print(i)

#Answer:
# Before updating Street name
# {'_id': ObjectId('63a18272cdbec8b764825826'), 'Name': 'Gerald', 'Phone number': '9638521476', 
#  'Address': {'Door_no': '86', 'Street_name': 'M.A.koil street', 'Area': 'butt road', 'State': 'Tamilnadu', 'Pincode': '123456'}}

#After updating Street name:
# {'_id': ObjectId('63a18272cdbec8b764825826'), 'Name': 'Gerald', 'Phone number': '9638521476',
#  'Address': {'Door_no': '86', 'Street_name': 'Silver street', 'Area': 'butt road', 'State': 'Tamilnadu', 'Pincode': '123456'}

{'_id': ObjectId('63a18272cdbec8b764825826'), 'Name': 'Gerald', 'Phone number': '9638521476', 'Address': {'Door_no': '86', 'Street_name': 'Silver street', 'Area': 'butt road', 'State': 'Tamilnadu', 'Pincode': '123456'}}

In [62]:
v=db.phonebook.delete_one({"Name":"Tim"})
for i in db.phonebook.find():
  print(i)
# Answer:
# The record with name "Tim" has been deleted

{'_id': ObjectId('63a17edbcdbec8b76482581f'), 'Name': 'Xavier', 'Phone number': '1234567894', 'Address': {'Door_no': '4/70', 'Street_name': 'St.Antony street', 'Area': 'St.Thomas Mount', 'State': 'Tamil nadu', 'Pincode': '123456'}}
{'_id': ObjectId('63a181afcdbec8b764825822'), 'Name': 'Monisha', 'Phone number': '4567891235', 'Address': {'Door_no': '12', 'Street_name': 'gold street', 'Area': 'bangalore', 'State': 'karnataka', 'Pincode': '235614'}}
{'_id': ObjectId('63a18272cdbec8b764825826'), 'Name': 'Gerald', 'Phone number': '9638521476', 'Address': {'Door_no': '86', 'Street_name': 'Silver street', 'Area': 'butt road', 'State': 'Tamilnadu', 'Pincode': '123456'}}